# Generated by Django 4.0.6 on 2023-08-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snackshelf',
            name='type',
            field=models.CharField(choices=[('snack', 'Snack'), ('candy', 'Candy'), ('sundry', 'Sundry'), ('warmfood', 'Warmfood')], max_length=100),
        ),
    ]
