# Generated by Django 4.2.4 on 2023-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_snackshelf_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianceCalculatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('previous_day_end_count', models.PositiveIntegerField(verbose_name='Previous Day End Count')),
                ('inventory_sold', models.PositiveIntegerField(verbose_name='Inventory Sold')),
                ('added_inventory', models.PositiveIntegerField(verbose_name='Added to Inventory')),
                ('transferred_inventory', models.PositiveIntegerField(verbose_name='Transferred Inventory')),
                ('previous_day_sales', models.PositiveIntegerField(verbose_name='Previous Day Sales')),
                ('end_count', models.PositiveIntegerField(verbose_name='End Count')),
            ],
            options={
                'verbose_name': 'Variance Calculator Entry',
                'verbose_name_plural': 'Variance Calculator Entries',
                'ordering': ['-date'],
            },
        ),
    ]
