# Generated by Django 4.2.4 on 2023-08-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_variancecalculatorentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='variancecalculatorentry',
            name='book_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Book Count'),
        ),
        migrations.AddField(
            model_name='variancecalculatorentry',
            name='variance',
            field=models.IntegerField(default=0, verbose_name='Variance'),
        ),
    ]
