# Generated by Django 4.2.4 on 2023-08-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_variancecalculatorentry_book_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variancecalculatorentry',
            name='section',
            field=models.CharField(blank=True, choices=[('snackshelf', 'Snack Shelf'), ('freezer', 'Freezer'), ('beverage', 'Beverage Cooler')], max_length=10, null=True),
        ),
    ]
