# Generated by Django 4.2.4 on 2023-08-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_variancecalculatorentry_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variancecalculatorentry',
            name='inventory_sold',
        ),
    ]
