# Generated by Django 4.2.4 on 2023-08-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_variancecalculatorentry_inventory_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variancecalculatorentry',
            name='transferred_inventory',
        ),
    ]
